// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accent': string;
  'active': string;
  'b': string;
  'b-img': string;
  'b-pb': string;
  'b-pt': string;
  'b-ptb': string;
  'bold': string;
  'btn': string;
  'clearfix': string;
  'clickable': string;
  'content': string;
  'content-data': string;
  'contentBox': string;
  'contentBoxSection': string;
  'fl': string;
  'fl-box': string;
  'fr': string;
  'hidden': string;
  'ie6': string;
  'ie7': string;
  'important': string;
  'index_main_item': string;
  'index_main_section': string;
  'input': string;
  'inputBtn': string;
  'left': string;
  'liFlex': string;
  'liFlexTitle': string;
  'mainStyle': string;
  'mth': string;
  'mtp': string;
  'nav-item': string;
  'nav-menu': string;
  'right': string;
  'semi': string;
  'tac': string;
  'tal': string;
  'tar': string;
  'title': string;
  'ulText': string;
  'veryBig': string;
  'w100': string;
}
export const cssExports: CssExports;
export default cssExports;
