// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'btn': string;
  'content': string;
  'index_main_item': string;
  'index_main_section': string;
  'input': string;
  'inputBtn': string;
  'left': string;
  'nav-item': string;
  'nav-menu': string;
  'right': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
