// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'b-img': string;
  'b-pb': string;
  'b-pt': string;
  'b-ptb': string;
  'bold': string;
  'fl': string;
  'fl-box': string;
  'fr': string;
  'hidden': string;
  'important': string;
  'mainStyle': string;
  'tac': string;
  'tal': string;
  'tar': string;
  'w100': string;
}
export const cssExports: CssExports;
export default cssExports;
