// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clearfix': string;
  'clickable': string;
  'content-data': string;
  'ie6': string;
  'ie7': string;
}
export const cssExports: CssExports;
export default cssExports;
