// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnWrp': string;
  'button': string;
  'header': string;
  'marginBtn': string;
  'marginTop': string;
  'material-icons': string;
  'textarea': string;
}
export const cssExports: CssExports;
export default cssExports;
