// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'info': string;
  'section_apps': string;
}
export const cssExports: CssExports;
export default cssExports;
