// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'content': string;
  'header-box': string;
  'hidden': string;
  'index_main_item': string;
  'index_main_section': string;
  'langToggle': string;
  'langToggleItem': string;
  'left': string;
  'logo': string;
  'main_nav_menu': string;
  'navItem': string;
  'navMenu': string;
  'right': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
