// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'header-box': string;
  'hidden': string;
  'index_main_item': string;
  'index_main_section': string;
  'left': string;
  'main_nav_menu': string;
  'nav-item': string;
  'nav-menu': string;
  'right': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
