// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'LINK': string;
  'PRIMARY': string;
  'disabled': string;
}
export const cssExports: CssExports;
export default cssExports;
